### ISSUE TITLE
Requires setuptools

### ISSUE THREAD

**Issue by honzajavorek** [liskin/strava-offline#8]
Hi! I installed the package using Poetry 1.2.2 and Python 3.10.6 (macOS, homebrew, pyenv). Running strava-offline results in:

```
Traceback (most recent call last):
  File "/Users/honza/Library/Caches/pypoetry/virtualenvs/honzajavorekcz-99qNy8GJ-py3.10/bin/strava-offline", line 5, in <module>
    from strava_offline.cli import cli
  File "/Users/honza/Library/Caches/pypoetry/virtualenvs/honzajavorekcz-99qNy8GJ-py3.10/lib/python3.10/site-packages/strava_offline/__init__.py", line 2, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
```

I found [this solution](https://stackoverflow.com/a/10538412/325365):

```
$ poetry add setuptools
$ poetry add strava-offline
```

Then running strava-offline lists its commands. Not sure whether this is expected behavior or a bug.

**Comment by liskin** [comment]
Not really expected, there was an undeclared runtime dependency on setuptools. That may have been fine in the Python packaging world in the past, or maybe not, I really don't know. Switched to `importlib.metadata` and added a test for this. Should be fine now. Will port to my other Python projects later. Do you need me to push a PyPI release immediately?

**Comment by liskin** [comment]
Actually, there was an unreleased bugfix here for a while so I did a release anyway.

**Comment by honzajavorek** [comment]
Thanks! Having setuptools in my own dependencies was enough as a workaround, but this is, of course, awesome :)
